name: my-workflow
version: 1
description: Default OpenSpec workflow - vision → use-case
artifacts:
  - id: Vision and Business Case
    generates: vision.md
    description: Describes the high-level goals and constraints, the business case, and provides an executive summary.
    template: vision.md
    instruction: >
    requires: []
  - id: Use Case fully dressed
    generates: UC{{#}}.md
    description: Describe the functional requirements in fully dressed format.
    template: use-case-fully-dressed.md
    instruction: INVOKE this link -> "./instructions/Use Case Model.md"
    requires: [vision]
  - id: Use Case brief
    generates: UC{{#}}.md
    description: Describe the functional requirements in brief format.
    template: use-case-brief.md
    instruction: INVOKE this link -> "./instructions/Use Case Model.md"
    requires: [vision]